services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - qp_network
    ports:
      - "8000:8000"
    volumes:
      - ./qp_backend:/qp_backend
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: my-postgres2
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${DATABASE_HOST} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - qp_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container2
    ports:
      - "6379:6379"
    networks:
      - qp_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  qp_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
